### ISSUE TITLE
fresh release

### ISSUE THREAD

**Issue by yegor256** [yegor256/threecopies#25]

**Comment by yegor256** [comment]
@rultor release, tag is `0.4.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.4.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.4.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.4.0`

**Comment by 0crat** [comment]
Job `gh:yegor256/threecopies#25` is not assigned, can't get performer
