### ISSUE TITLE
containers are not terminated on overtime

### ISSUE THREAD

**Issue by yegor256** [yegor256/threecopies#4]
Let's fix

**Comment by 0crat** [comment]
Job `gh:yegor256/threecopies#4` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+3045](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
working fine now

**Comment by 0crat** [comment]
Job `gh:yegor256/threecopies#4` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+3120](http://www.0crat.com/u/yegor256).
