### ISSUE TITLE
doesn't run every hour

### ISSUE THREAD

**Issue by yegor256** [yegor256/threecopies#5]
It's a bug

**Comment by 0crat** [comment]
Job `gh:yegor256/threecopies#5` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+3060](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Job `gh:yegor256/threecopies#5` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+3090](http://www.0crat.com/u/yegor256).
